---
micronaut:
  security:
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: devSecretItsVeryVerySecretSecret
---
datasources:
  default:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: 'postgres'
    password: 'pass'
---
app-config:
  http-communication-logging:
    enabled: true
admin-auth:
  username: user
  password: pass3j4hkhk23hk23k232hk3h232
