---
micronaut:
  security:
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: devSecretItsVeryVerySecretSecret
---
datasources:
  default:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: 'postgres'
    password: 'pass'
---
admin-auth-config:
  user: user
  password: pass
